/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PublicUserProfile {
  'id' : Principal,
  'name' : string,
  'isAvailableAsTasker' : boolean,
  'rating' : bigint,
  'phone' : [] | [string],
  'location' : string,
  'walletBalance' : bigint,
  'upiId' : [] | [string],
  'aadharOrStudentId' : [] | [string],
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Task {
  'id' : bigint,
  'tip' : [] | [bigint],
  'status' : TaskStatus,
  'completedAt' : [] | [bigint],
  'title' : string,
  'otpCode' : bigint,
  'customerLocation' : string,
  'taskerRating' : [] | [bigint],
  'otpVerified' : boolean,
  'createdAt' : bigint,
  'customerRating' : [] | [bigint],
  'description' : string,
  'taskerId' : [] | [Principal],
  'storeLocation' : string,
  'customerId' : Principal,
  'acceptedAt' : [] | [bigint],
  'amount' : bigint,
}
export type TaskResult = { 'ok' : Task } |
  { 'err' : string };
export interface TaskStats {
  'totalTasks' : bigint,
  'completedTasks' : bigint,
  'totalFees' : bigint,
  'totalUsers' : bigint,
  'activeTasks' : bigint,
  'cancelledTasks' : bigint,
}
export type TaskStatus = { 'cancelled' : null } |
  { 'completed' : null } |
  { 'delivered' : null } |
  { 'accepted' : null } |
  { 'inProgress' : null } |
  { 'posted' : null };
export interface TaskUpdateRequest {
  'tip' : [] | [bigint],
  'title' : string,
  'customerLocation' : string,
  'description' : string,
  'storeLocation' : string,
  'amount' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type PaymentStatus = { 'success' : null } | { 'failed' : null } | { 'pending' : null };
export interface PaymentLog {
  'id' : bigint,
  'taskId' : bigint,
  'userPaid' : bigint,
  'taskerEarnings' : bigint,
  'platformFee' : bigint,
  'status' : PaymentStatus,
  'date' : bigint,
}
export type PayoutStatus = { 'pending' : null } | { 'paid' : null };
export type PayoutMethod = { 'upi' : null } | { 'cash' : null };
export interface PayoutRecord {
  'taskId' : bigint,
  'taskerId' : Principal,
  'amount' : bigint,
  'status' : PayoutStatus,
  'method' : [] | [PayoutMethod],
  'createdDate' : bigint,
  'paidDate' : [] | [bigint],
}

export type PickupDropTaskStatus =
  | { 'open' : null }
  | { 'accepted' : null }
  | { 'inProgress' : null }
  | { 'delivered' : null }
  | { 'completed' : null }
  | { 'failed' : null }
  | { 'cancelled' : null };

export interface PickupDropTask {
  'id' : bigint,
  'pickupOwnerName' : string,
  'pickupContact' : string,
  'pickupLocation' : string,
  'dropOwnerName' : string,
  'dropContact' : string,
  'dropLocation' : string,
  'productWorth' : bigint,
  'taskerFee' : bigint,
  'boostFee' : bigint,
  'status' : PickupDropTaskStatus,
  'posterId' : Principal,
  'createdAt' : bigint,
}

export interface PickupDropActiveTask {
  'taskId' : bigint,
  'taskerId' : Principal,
  'paymentDone' : boolean,
  'status' : PickupDropTaskStatus,
  'otpPickup' : bigint,
  'otpDelivery' : bigint,
  'acceptedAt' : bigint,
  'completedAt' : [] | [bigint],
}

export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptTask' : ActorMethod<[bigint], TaskResult>,
  'adminCancelTask' : ActorMethod<[bigint], TaskResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelTask' : ActorMethod<[bigint], TaskResult>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createTask' : ActorMethod<
    [string, string, bigint, [] | [bigint], string, string],
    bigint
  >,
  'getAvailableTasks' : ActorMethod<[], Array<Task>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [PublicUserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEarningsHistory' : ActorMethod<[], Array<Task>>,
  'getMyAcceptedTasks' : ActorMethod<[], Array<Task>>,
  'getMyPostedTasks' : ActorMethod<[], Array<Task>>,
  'getPaymentLogs' : ActorMethod<[], Array<PaymentLog>>,
  'getPayoutRecords' : ActorMethod<[], Array<PayoutRecord>>,
  'getPlatformStats' : ActorMethod<[], TaskStats>,
  'getRatingCount' : ActorMethod<[Principal], bigint>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTaskById' : ActorMethod<[bigint], TaskResult>,
  'getUserProfile' : ActorMethod<[Principal], PublicUserProfile>,
  'getWalletBalance' : ActorMethod<[], bigint>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAllUserProfiles' : ActorMethod<[], Array<PublicUserProfile>>,
  'debugUsersCount' : ActorMethod<[], bigint>,
  'debugTasksCount' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'markPayoutPaid' : ActorMethod<[bigint, PayoutMethod], boolean>,
  'markTaskDelivered' : ActorMethod<[bigint], TaskResult>,
  'markTaskInProgress' : ActorMethod<[bigint], TaskResult>,
  'rateTask' : ActorMethod<[bigint, bigint], boolean>,
  'saveCallerUserProfile' : ActorMethod<[PublicUserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateProfile' : ActorMethod<
    [string, [] | [string], string, boolean, [] | [string], [] | [string]],
    undefined
  >,
  'updateTask' : ActorMethod<[bigint, TaskUpdateRequest], undefined>,
  'verifyOtp' : ActorMethod<[bigint, bigint], boolean>,
  'acceptPickupDropTask' : ActorMethod<[bigint], boolean>,
  'createPickupDropTask' : ActorMethod<[string, string, string, string, string, string, bigint, bigint, bigint], bigint>,
  'getAvailablePickupDropTasks' : ActorMethod<[], Array<PickupDropTask>>,
  'getAllPickupDropTasks' : ActorMethod<[], Array<PickupDropTask>>,
  'getMyPostedPickupDropTasks' : ActorMethod<[], Array<PickupDropTask>>,
  'getMyActivePickupDropTasks' : ActorMethod<[], Array<[PickupDropTask, PickupDropActiveTask]>>,
  'getPickupDropTaskById' : ActorMethod<[bigint], [] | [PickupDropTask]>,
  'getPickupDropActiveTaskById' : ActorMethod<[bigint], [] | [PickupDropActiveTask]>,
  'markPickupDropDelivered' : ActorMethod<[bigint], boolean>,
  'markPickupDropInProgress' : ActorMethod<[bigint], boolean>,
  'verifyPickupDropOtp' : ActorMethod<[bigint, bigint], boolean>,
  'adminCancelPickupDropTask' : ActorMethod<[bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
