/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TaskStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'delivered' : IDL.Null,
  'accepted' : IDL.Null,
  'inProgress' : IDL.Null,
  'posted' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'tip' : IDL.Opt(IDL.Nat),
  'status' : TaskStatus,
  'completedAt' : IDL.Opt(IDL.Int),
  'title' : IDL.Text,
  'otpCode' : IDL.Nat,
  'customerLocation' : IDL.Text,
  'taskerRating' : IDL.Opt(IDL.Nat),
  'otpVerified' : IDL.Bool,
  'createdAt' : IDL.Int,
  'customerRating' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
  'taskerId' : IDL.Opt(IDL.Principal),
  'storeLocation' : IDL.Text,
  'customerId' : IDL.Principal,
  'acceptedAt' : IDL.Opt(IDL.Int),
  'amount' : IDL.Nat,
});
export const TaskResult = IDL.Variant({ 'ok' : Task, 'err' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const PublicUserProfile = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'isAvailableAsTasker' : IDL.Bool,
  'rating' : IDL.Nat,
  'phone' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
  'walletBalance' : IDL.Nat,
  'upiId' : IDL.Opt(IDL.Text),
});
export const TaskStats = IDL.Record({
  'totalTasks' : IDL.Nat,
  'completedTasks' : IDL.Nat,
  'totalFees' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'activeTasks' : IDL.Nat,
  'cancelledTasks' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TaskUpdateRequest = IDL.Record({
  'tip' : IDL.Opt(IDL.Nat),
  'title' : IDL.Text,
  'customerLocation' : IDL.Text,
  'description' : IDL.Text,
  'storeLocation' : IDL.Text,
  'amount' : IDL.Nat,
});
export const PaymentStatus = IDL.Variant({
  'success' : IDL.Null,
  'failed' : IDL.Null,
  'pending' : IDL.Null,
});
export const PaymentLog = IDL.Record({
  'id' : IDL.Nat,
  'taskId' : IDL.Nat,
  'userPaid' : IDL.Nat,
  'taskerEarnings' : IDL.Nat,
  'platformFee' : IDL.Nat,
  'status' : PaymentStatus,
  'date' : IDL.Int,
});
export const PayoutStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
});
export const PayoutMethod = IDL.Variant({
  'upi' : IDL.Null,
  'cash' : IDL.Null,
});
export const PayoutRecord = IDL.Record({
  'taskId' : IDL.Nat,
  'taskerId' : IDL.Principal,
  'amount' : IDL.Nat,
  'status' : PayoutStatus,
  'method' : IDL.Opt(PayoutMethod),
  'createdDate' : IDL.Int,
  'paidDate' : IDL.Opt(IDL.Int),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptTask' : IDL.Func([IDL.Nat], [TaskResult], []),
  'adminCancelTask' : IDL.Func([IDL.Nat], [TaskResult], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelTask' : IDL.Func([IDL.Nat], [TaskResult], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createTask' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Nat), IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAvailableTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(PublicUserProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEarningsHistory' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getMyAcceptedTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getMyPostedTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getPaymentLogs' : IDL.Func([], [IDL.Vec(PaymentLog)], ['query']),
  'getPayoutRecords' : IDL.Func([], [IDL.Vec(PayoutRecord)], ['query']),
  'getPlatformStats' : IDL.Func([], [TaskStats], ['query']),
  'getRatingCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTaskById' : IDL.Func([IDL.Nat], [TaskResult], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [PublicUserProfile], ['query']),
  'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(PublicUserProfile)], ['query']),
  'debugUsersCount' : IDL.Func([], [IDL.Nat], ['query']),
  'debugTasksCount' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markPayoutPaid' : IDL.Func([IDL.Nat, PayoutMethod], [IDL.Bool], []),
  'markTaskDelivered' : IDL.Func([IDL.Nat], [TaskResult], []),
  'markTaskInProgress' : IDL.Func([IDL.Nat], [TaskResult], []),
  'rateTask' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([PublicUserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateTask' : IDL.Func([IDL.Nat, TaskUpdateRequest], [], []),
  'verifyOtp' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TaskStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'delivered' : IDL.Null,
    'accepted' : IDL.Null,
    'inProgress' : IDL.Null,
    'posted' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'tip' : IDL.Opt(IDL.Nat),
    'status' : TaskStatus,
    'completedAt' : IDL.Opt(IDL.Int),
    'title' : IDL.Text,
    'otpCode' : IDL.Nat,
    'customerLocation' : IDL.Text,
    'taskerRating' : IDL.Opt(IDL.Nat),
    'otpVerified' : IDL.Bool,
    'createdAt' : IDL.Int,
    'customerRating' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
    'taskerId' : IDL.Opt(IDL.Principal),
    'storeLocation' : IDL.Text,
    'customerId' : IDL.Principal,
    'acceptedAt' : IDL.Opt(IDL.Int),
    'amount' : IDL.Nat,
  });
  const TaskResult = IDL.Variant({ 'ok' : Task, 'err' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const PublicUserProfile = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'isAvailableAsTasker' : IDL.Bool,
    'rating' : IDL.Nat,
    'phone' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
    'walletBalance' : IDL.Nat,
    'upiId' : IDL.Opt(IDL.Text),
  });
  const TaskStats = IDL.Record({
    'totalTasks' : IDL.Nat,
    'completedTasks' : IDL.Nat,
    'totalFees' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'activeTasks' : IDL.Nat,
    'cancelledTasks' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TaskUpdateRequest = IDL.Record({
    'tip' : IDL.Opt(IDL.Nat),
    'title' : IDL.Text,
    'customerLocation' : IDL.Text,
    'description' : IDL.Text,
    'storeLocation' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const PaymentStatus = IDL.Variant({
    'success' : IDL.Null,
    'failed' : IDL.Null,
    'pending' : IDL.Null,
  });
  const PaymentLog = IDL.Record({
    'id' : IDL.Nat,
    'taskId' : IDL.Nat,
    'userPaid' : IDL.Nat,
    'taskerEarnings' : IDL.Nat,
    'platformFee' : IDL.Nat,
    'status' : PaymentStatus,
    'date' : IDL.Int,
  });
  const PayoutStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
  });
  const PayoutMethod = IDL.Variant({
    'upi' : IDL.Null,
    'cash' : IDL.Null,
  });
  const PayoutRecord = IDL.Record({
    'taskId' : IDL.Nat,
    'taskerId' : IDL.Principal,
    'amount' : IDL.Nat,
    'status' : PayoutStatus,
    'method' : IDL.Opt(PayoutMethod),
    'createdDate' : IDL.Int,
    'paidDate' : IDL.Opt(IDL.Int),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptTask' : IDL.Func([IDL.Nat], [TaskResult], []),
    'adminCancelTask' : IDL.Func([IDL.Nat], [TaskResult], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelTask' : IDL.Func([IDL.Nat], [TaskResult], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createTask' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Nat), IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAvailableTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(PublicUserProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEarningsHistory' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getMyAcceptedTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getMyPostedTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getPaymentLogs' : IDL.Func([], [IDL.Vec(PaymentLog)], ['query']),
    'getPayoutRecords' : IDL.Func([], [IDL.Vec(PayoutRecord)], ['query']),
    'getPlatformStats' : IDL.Func([], [TaskStats], ['query']),
    'getRatingCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTaskById' : IDL.Func([IDL.Nat], [TaskResult], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [PublicUserProfile],
        ['query'],
      ),
    'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(PublicUserProfile)], ['query']),
    'debugUsersCount' : IDL.Func([], [IDL.Nat], ['query']),
    'debugTasksCount' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markPayoutPaid' : IDL.Func([IDL.Nat, PayoutMethod], [IDL.Bool], []),
    'markTaskDelivered' : IDL.Func([IDL.Nat], [TaskResult], []),
    'markTaskInProgress' : IDL.Func([IDL.Nat], [TaskResult], []),
    'rateTask' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([PublicUserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateTask' : IDL.Func([IDL.Nat, TaskUpdateRequest], [], []),
    'verifyOtp' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };
