/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type TaskResult = {
    __kind__: "ok";
    ok: Task;
} | {
    __kind__: "err";
    err: string;
};
export interface TaskStats {
    totalTasks: bigint;
    completedTasks: bigint;
    totalFees: bigint;
    totalUsers: bigint;
    activeTasks: bigint;
    cancelledTasks: bigint;
}
export type PaymentStatus = { __kind__: "success" } | { __kind__: "failed" } | { __kind__: "pending" };
export interface PaymentLog {
    id: bigint;
    taskId: bigint;
    userPaid: bigint;
    taskerEarnings: bigint;
    platformFee: bigint;
    status: PaymentStatus;
    date: bigint;
}
export type PayoutStatus = { __kind__: "pending" } | { __kind__: "paid" };
export type PayoutMethod = { __kind__: "upi" } | { __kind__: "cash" };
export interface PayoutRecord {
    taskId: bigint;
    taskerId: Principal;
    amount: bigint;
    status: PayoutStatus;
    method?: PayoutMethod;
    createdDate: bigint;
    paidDate?: bigint;
}
export interface Task {
    id: bigint;
    tip?: bigint;
    status: TaskStatus;
    completedAt?: bigint;
    title: string;
    otpCode: bigint;
    customerLocation: string;
    taskerRating?: bigint;
    otpVerified: boolean;
    createdAt: bigint;
    customerRating?: bigint;
    description: string;
    taskerId?: Principal;
    storeLocation: string;
    customerId: Principal;
    acceptedAt?: bigint;
    amount: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface PublicUserProfile {
    id: Principal;
    name: string;
    isAvailableAsTasker: boolean;
    rating: bigint;
    phone?: string;
    location: string;
    walletBalance: bigint;
    upiId?: string;
}
export interface TaskUpdateRequest {
    tip?: bigint;
    title: string;
    customerLocation: string;
    description: string;
    storeLocation: string;
    amount: bigint;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export enum TaskStatus {
    cancelled = "cancelled",
    completed = "completed",
    delivered = "delivered",
    accepted = "accepted",
    inProgress = "inProgress",
    posted = "posted"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptTask(taskId: bigint): Promise<TaskResult>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelTask(taskId: bigint): Promise<TaskResult>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createTask(title: string, description: string, amount: bigint, tip: bigint | null, customerLocation: string, storeLocation: string): Promise<bigint>;
    getAvailableTasks(): Promise<Array<Task>>;
    getCallerUserProfile(): Promise<PublicUserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEarningsHistory(): Promise<Array<Task>>;
    getMyAcceptedTasks(): Promise<Array<Task>>;
    getMyPostedTasks(): Promise<Array<Task>>;
    getPlatformStats(): Promise<TaskStats>;
    getRatingCount(user: Principal): Promise<bigint>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTaskById(id: bigint): Promise<TaskResult>;
    getUserProfile(user: Principal): Promise<PublicUserProfile>;
    getWalletBalance(): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    markTaskDelivered(taskId: bigint): Promise<TaskResult>;
    markTaskInProgress(taskId: bigint): Promise<TaskResult>;
    rateTask(taskId: bigint, stars: bigint): Promise<boolean>;
    saveCallerUserProfile(profile: PublicUserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateProfile(name: string, phone: string | null, location: string, isAvailableAsTasker: boolean, upiId: string | null, aadharOrStudentId: string | null): Promise<void>;
    updateTask(taskId: bigint, update: TaskUpdateRequest): Promise<void>;
    adminCancelTask(taskId: bigint): Promise<TaskResult>;
    getAllTasks(): Promise<Array<Task>>;
    getAllUserProfiles(): Promise<Array<PublicUserProfile>>;
    getPaymentLogs(): Promise<Array<PaymentLog>>;
    getPayoutRecords(): Promise<Array<PayoutRecord>>;
    markPayoutPaid(taskId: bigint, method: PayoutMethod): Promise<boolean>;
    verifyOtp(taskId: bigint, otp: bigint): Promise<boolean>;
    fetchYouTubeRss(channelId: string): Promise<string>;
}
import type { PublicUserProfile as _PublicUserProfile, StripeSessionStatus as _StripeSessionStatus, Task as _Task, TaskResult as _TaskResult, TaskStatus as _TaskStatus, TaskUpdateRequest as _TaskUpdateRequest, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptTask(arg0: bigint): Promise<TaskResult> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptTask(arg0);
                return from_candid_TaskResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptTask(arg0);
            return from_candid_TaskResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelTask(arg0: bigint): Promise<TaskResult> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelTask(arg0);
                return from_candid_TaskResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelTask(arg0);
            return from_candid_TaskResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createTask(arg0: string, arg1: string, arg2: bigint, arg3: bigint | null, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, arg2, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, arg2, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async getAvailableTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableTasks();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableTasks();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<PublicUserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEarningsHistory(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEarningsHistory();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEarningsHistory();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAcceptedTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAcceptedTasks();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAcceptedTasks();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPostedTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPostedTasks();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPostedTasks();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlatformStats(): Promise<TaskStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformStats();
            return result;
        }
    }
    async getRatingCount(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getRatingCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRatingCount(arg0);
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTaskById(arg0: bigint): Promise<TaskResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaskById(arg0);
                return from_candid_TaskResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaskById(arg0);
            return from_candid_TaskResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<PublicUserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_PublicUserProfile_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_PublicUserProfile_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWalletBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getWalletBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWalletBalance();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async markTaskDelivered(arg0: bigint): Promise<TaskResult> {
        if (this.processError) {
            try {
                const result = await this.actor.markTaskDelivered(arg0);
                return from_candid_TaskResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markTaskDelivered(arg0);
            return from_candid_TaskResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async markTaskInProgress(arg0: bigint): Promise<TaskResult> {
        if (this.processError) {
            try {
                const result = await this.actor.markTaskInProgress(arg0);
                return from_candid_TaskResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markTaskInProgress(arg0);
            return from_candid_TaskResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async rateTask(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rateTask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rateTask(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: PublicUserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_PublicUserProfile_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_PublicUserProfile_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: string | null, arg2: string, arg3: boolean, arg4: string | null, arg5: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateTask(arg0: bigint, arg1: TaskUpdateRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, to_candid_TaskUpdateRequest_n26(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, to_candid_TaskUpdateRequest_n26(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async verifyOtp(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyOtp(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyOtp(arg0, arg1);
            return result;
        }
    }
    async adminCancelTask(arg0: bigint): Promise<TaskResult> {
        const actor = this.actor as any;
        if (this.processError) {
            try {
                const result = await actor.adminCancelTask(arg0);
                return from_candid_TaskResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else {
            const result = await actor.adminCancelTask(arg0);
            return from_candid_TaskResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        const actor = this.actor as any;
        if (this.processError) {
            try {
                const result = await actor.getAllTasks();
                return result.map((t: any) => from_candid_Task_n3(this._uploadFile, this._downloadFile, t));
            } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else {
            const result = await actor.getAllTasks();
            return result.map((t: any) => from_candid_Task_n3(this._uploadFile, this._downloadFile, t));
        }
    }
    async getAllUserProfiles(): Promise<Array<PublicUserProfile>> {
        const actor = this.actor as any;
        if (this.processError) {
            try {
                const result = await actor.getAllUserProfiles();
                return result.map((p: any) => from_candid_PublicUserProfile_n15(this._uploadFile, this._downloadFile, p));
            } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else {
            const result = await actor.getAllUserProfiles();
            return result.map((p: any) => from_candid_PublicUserProfile_n15(this._uploadFile, this._downloadFile, p));
        }
    }
    async getPaymentLogs(): Promise<Array<PaymentLog>> {
        const actor = this.actor as any;
        if (this.processError) {
            try { return await actor.getPaymentLogs(); }
            catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await actor.getPaymentLogs(); }
    }
    async getPayoutRecords(): Promise<Array<PayoutRecord>> {
        const actor = this.actor as any;
        if (this.processError) {
            try { return await actor.getPayoutRecords(); }
            catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await actor.getPayoutRecords(); }
    }
    async markPayoutPaid(arg0: bigint, arg1: PayoutMethod): Promise<boolean> {
        const actor = this.actor as any;
        const candid_method = arg1.__kind__ === "upi" ? { upi: null } : { cash: null };
        if (this.processError) {
            try { return await actor.markPayoutPaid(arg0, candid_method); }
            catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await actor.markPayoutPaid(arg0, candid_method); }
    }
    async fetchYouTubeRss(channelId: string): Promise<string> {
        const actor = this.actor as any;
        if (this.processError) {
            try { return await actor.fetchYouTubeRss(channelId); }
            catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await actor.fetchYouTubeRss(channelId); }
    }
}
function from_candid_PublicUserProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicUserProfile): PublicUserProfile {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_TaskResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskResult): TaskResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PublicUserProfile]): PublicUserProfile | null {
    return value.length === 0 ? null : from_candid_PublicUserProfile_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    isAvailableAsTasker: boolean;
    rating: bigint;
    phone: [] | [string];
    location: string;
    walletBalance: bigint;
    upiId: [] | [string];
    aadharOrStudentId: [] | [string];
}): {
    id: Principal;
    name: string;
    isAvailableAsTasker: boolean;
    rating: bigint;
    phone?: string;
    location: string;
    walletBalance: bigint;
    upiId?: string;
    aadharOrStudentId?: string;
} {
    return {
        id: value.id,
        name: value.name,
        isAvailableAsTasker: value.isAvailableAsTasker,
        rating: value.rating,
        phone: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.phone)),
        location: value.location,
        walletBalance: value.walletBalance,
        upiId: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.upiId)),
        aadharOrStudentId: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.aadharOrStudentId))
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    tip: [] | [bigint];
    status: _TaskStatus;
    completedAt: [] | [bigint];
    title: string;
    otpCode: bigint;
    customerLocation: string;
    taskerRating: [] | [bigint];
    otpVerified: boolean;
    createdAt: bigint;
    customerRating: [] | [bigint];
    description: string;
    taskerId: [] | [Principal];
    storeLocation: string;
    customerId: Principal;
    acceptedAt: [] | [bigint];
    amount: bigint;
}): {
    id: bigint;
    tip?: bigint;
    status: TaskStatus;
    completedAt?: bigint;
    title: string;
    otpCode: bigint;
    customerLocation: string;
    taskerRating?: bigint;
    otpVerified: boolean;
    createdAt: bigint;
    customerRating?: bigint;
    description: string;
    taskerId?: Principal;
    storeLocation: string;
    customerId: Principal;
    acceptedAt?: bigint;
    amount: bigint;
} {
    return {
        id: value.id,
        tip: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.tip)),
        status: from_candid_TaskStatus_n6(_uploadFile, _downloadFile, value.status),
        completedAt: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.completedAt)),
        title: value.title,
        otpCode: value.otpCode,
        customerLocation: value.customerLocation,
        taskerRating: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.taskerRating)),
        otpVerified: value.otpVerified,
        createdAt: value.createdAt,
        customerRating: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.customerRating)),
        description: value.description,
        taskerId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.taskerId)),
        storeLocation: value.storeLocation,
        customerId: value.customerId,
        acceptedAt: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.acceptedAt)),
        amount: value.amount
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Task;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Task;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Task_n3(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n22(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    completed: null;
} | {
    delivered: null;
} | {
    accepted: null;
} | {
    inProgress: null;
} | {
    posted: null;
}): TaskStatus {
    return "cancelled" in value ? TaskStatus.cancelled : "completed" in value ? TaskStatus.completed : "delivered" in value ? TaskStatus.delivered : "accepted" in value ? TaskStatus.accepted : "inProgress" in value ? TaskStatus.inProgress : "posted" in value ? TaskStatus.posted : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n3(_uploadFile, _downloadFile, x));
}
function to_candid_PublicUserProfile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PublicUserProfile): _PublicUserProfile {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_TaskUpdateRequest_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskUpdateRequest): _TaskUpdateRequest {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    isAvailableAsTasker: boolean;
    rating: bigint;
    phone?: string;
    location: string;
    walletBalance: bigint;
    upiId?: string;
    aadharOrStudentId?: string;
}): {
    id: Principal;
    name: string;
    isAvailableAsTasker: boolean;
    rating: bigint;
    phone: [] | [string];
    location: string;
    walletBalance: bigint;
    upiId: [] | [string];
    aadharOrStudentId: [] | [string];
} {
    return {
        id: value.id,
        name: value.name,
        isAvailableAsTasker: value.isAvailableAsTasker,
        rating: value.rating,
        phone: value.phone ? candid_some(value.phone) : candid_none(),
        location: value.location,
        walletBalance: value.walletBalance,
        upiId: value.upiId ? candid_some(value.upiId) : candid_none(),
        aadharOrStudentId: value.aadharOrStudentId ? candid_some(value.aadharOrStudentId) : candid_none()
    };
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tip?: bigint;
    title: string;
    customerLocation: string;
    description: string;
    storeLocation: string;
    amount: bigint;
}): {
    tip: [] | [bigint];
    title: string;
    customerLocation: string;
    description: string;
    storeLocation: string;
    amount: bigint;
} {
    return {
        tip: value.tip ? candid_some(value.tip) : candid_none(),
        title: value.title,
        customerLocation: value.customerLocation,
        description: value.description,
        storeLocation: value.storeLocation,
        amount: value.amount
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
